#!/usr/bin/env bash

set -e

script_path="$( dirname "$0" )"

# Import our functions.

source "$script_path"/submit-menus.fun
source "$script_path"/submit-xml.fun

# TODO: Add command line parsing here.

data_dir="$1"
if [[ ! -d "$data_dir" ]]; then
    printf "No such directory: %s\n" "$data_dir" >&2
    exit 1
fi

# Examine the XML files in $data_dir to figure out what they are.
# Creates the associative array xml_files with file names as keys and
# the top-level XML element as values.

declare -A xml_files

for f in "$data_dir"/*.xml; do
    xml_files["$(basename "$f")"]="$( xmlstarlet el "$f" | head -n 1 )"
done

do_main_menu
